apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: mint
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: youssefdev/user-service:mint
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: DB_PORT
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: ENVIRONMENT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DB_PASSWORD

